language: cpp
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - cmake
      - cxxtest

script:
  - mkdir build &&  cd build
  - cmake ..
  - cmake --build . -- -j4
  - cd test
  - ctest . -C Debug -V

after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/report.py > report.py
  - python report.py --include-as-cpputest *./cpputest*.xml --include-as-cute */cute*.xml --include-as-cxxtest */cxxtest.xml --include-as-gtest */gtest.xml
