language: cpp
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - cmake
      - cxxtest

script:
  - mkdir build &&  cd build
  - cmake ..
  - cmake --build . -- -j4
  - cd test
  - ctest . -C Debug -V

after_script:
  - ls
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py > upload.py
  - python upload.py --framework bandit
  - python upload.py --framework cpputest
  - python upload.py --framework cute --include *cute*.xml
  - python upload.py --framework cxxtest
